export const SAVE_TASK_REQUEST = "SAVE_TASK_REQUEST";
export const FETCH_TASK_REQUEST = "FETCH_TASK_REQUEST";
export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const TASK_SUCCESS = "TASK_SUCCESS";
export const TASK_FAILURE = "TASK_FAILURE";
